Repository wanted-pre-onboarding-frontend-12team/pre-onboarding-7th-3-2-12, pull requests merged in 2022-11, with the labels that each got.

#3 [#1, #2]
  client/package.json
  client/src/App.tsx
  client/src/assets/icons/AccountIcon.svg
  client/src/assets/icons/DecemberIcon.png
  client/src/assets/icons/UserIcon.svg
  client/src/assets/icons/index.ts
  client/src/assets/icons/logo.png
  client/src/components/layout/Footer/index.tsx
  client/src/components/layout/Header/index.tsx
  client/src/components/layout/Sidebar/index.tsx
  client/src/components/layout/index.ts
  client/src/index.tsx
  client/src/pages/Board/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/index.ts
  client/src/router/index.tsx
  client/src/router/routePath.ts
  client/src/utils/isValidArray.ts
Labels: 💄 UI

#5 [#1, #2] 로그인시 로컬 스토리지에 accessToken 저장 및 사이드 바 UI 수정
  client/src/apis/login.ts
  client/src/apis/requester.ts
  client/src/assets/icons/DashboardIcon.svg
  client/src/assets/icons/DecemberIcon.png
  client/src/assets/icons/LogoutIcon.svg
  client/src/assets/icons/index.ts
  client/src/components/layout/Sidebar/index.tsx
  client/src/pages/Login/index.tsx
Labels: ✨ Feature, 🌐 API, 💄 UI

#8 계좌목록 UI 구현
  client/src/apis/bankAccount.ts
  client/src/apis/requester.ts
  client/src/components/feature/AccountGrid/index.tsx
  client/src/components/index.ts
  client/src/components/shared/DropDown/index.tsx
  client/src/components/shared/SearchInput/index.tsx
  client/src/pages/BankAccount/index.tsx
  client/src/pages/Board/index.tsx
  client/src/pages/index.ts
  server/db.json
  server/yarn.lock
Labels: 💄 UI

#10 [#1, #2] private router 추가 및 localStorage에 name 추가
  client/src/apis/login.ts
  client/src/components/layout/Header/index.tsx
  client/src/core/apis/common.ts
  client/src/pages/Login/index.tsx
  client/src/router/index.tsx
  client/src/router/privateRouter.tsx
  client/src/router/routePath.ts
  client/src/types/api.ts
Labels: ✨ Feature

#12 [#11] 유저 목록 페이지에 필요한 데이터 변환 모듈 적용 & 유저 목록 테이블 UI 수정
  client/package.json
  client/src/components/feature/AccountGrid/index.tsx
  client/src/components/feature/UserGridTable/index.tsx
  client/src/components/index.ts
  client/src/components/layout/index.tsx
  client/src/components/shared/Button/index.tsx
  client/src/core/adminDataConverter.ts
  client/src/pages/BankAccount/index.tsx
  client/src/pages/Users/index.tsx
  client/src/pages/index.ts
  client/src/router/index.tsx
  client/yarn.lock
Labels: ✨ Feature, 💄 UI

#16 페이지네이션 컴포넌트 구현 & 공통 레이아웃 스타일링 수정
  client/src/components/feature/UserGridTable/index.tsx
  client/src/components/index.ts
  client/src/components/layout/Header/index.tsx
  client/src/components/layout/Sidebar/index.tsx
  client/src/components/layout/index.tsx
  client/src/components/shared/Pagenation/index.tsx
  client/src/core/apis/user.ts
  client/src/pages/Users/index.tsx
  server/db.json
Labels: ✨ Feature, 💄 UI

#17 [#1, #2] 로컬 스토리지 함수 수정 및 사이드바 UI 변경
  client/src/apis/requester.ts
  client/src/components/layout/Header/index.tsx
  client/src/components/layout/Sidebar/index.tsx
  client/src/pages/Login/index.tsx
  client/src/utils/sidebarList.ts
  client/src/utils/storage.ts
Labels: ✨ Feature, 💄 UI

#19 [#2] layout 감쌌을 때 나던 에러 수정
  client/src/components/layout/Sidebar/index.tsx
  client/src/utils/sidebarList.ts
Labels: 🎨 Structure

#20 [#14]사용자 상세 페이지 구현
  client/index.html
  client/src/apis/user.ts
  client/src/components/feature/CreateUser/UserInput/index.tsx
  client/src/components/feature/CreateUser/UserRadio/index.tsx
  client/src/components/feature/CreateUser/UserSelect/index.tsx
  client/src/components/feature/CreateUser/index.tsx
  client/src/components/feature/DetailUser/index.tsx
  client/src/components/feature/UserInfo/index.tsx
  client/src/shared/modal/index.tsx
  client/src/utils/makeUUID.ts
  client/src/utils/useUserStore.ts
Labels: ✨ Feature, 💄 UI

#21 [#14] 사용자 상세 route 추가
  client/src/router/index.tsx
  client/src/router/routePath.ts
Labels: ✨ Feature

#18 [#13] 유저 목록 상단 부분 구현
  client/src/components/feature/UserGridTable/index.tsx
  client/src/components/shared/DropDown/index.tsx
  client/src/components/shared/SearchInput/index.tsx
  client/src/core/apis/user.ts
  client/src/pages/BankAccount/index.tsx
  client/src/pages/Users/index.tsx
Labels: ✨ Feature, 💄 UI

#24 [#22, #23] 계좌 목록 & 계좌 상세 페이지 구현
  client/package.json
  client/src/apis/bankAccount.ts
  client/src/apis/requester.ts
  client/src/apis/user.ts
  client/src/components/feature/AccountGrid/index.tsx
  client/src/components/shared/Button/index.tsx
  client/src/components/shared/DropDown/index.tsx
  client/src/components/shared/Pagenation/index.tsx
  client/src/components/shared/SearchInput/index.tsx
  client/src/constants/account.ts
  client/src/constants/dropDown.ts
  client/src/constants/zustand.ts
  client/src/core/apis/account.ts
  client/src/hooks/useAccount.ts
  client/src/hooks/useAccountDetail.ts
  client/src/pages/Account/index.tsx
  client/src/pages/AccountDetail/index.tsx
  client/src/pages/BankAccount/index.tsx
  client/src/pages/Users/index.tsx
  client/src/pages/index.ts
  client/src/router/index.tsx
  client/src/router/routePath.ts
  client/src/types/api.ts
  client/src/utils/accountUtils.ts
  client/src/utils/dayUtils.ts
  client/src/utils/numberUtils.ts
  client/src/zustand/useAccountStore.ts
  client/yarn.lock
  server/db.json
  server/generateData.ts
Labels: ✨ Feature, 🌐 API, 💄 UI

#25 [#14] user 상세 조회 api 추가
  client/src/core/apis/user.ts
Labels: 🌐 API

#28 [#14] 사용자 이름 수정/ 계좌 목록 추가
  client/package.json
  client/src/components/feature/DetailUser/index.tsx
  client/src/components/feature/UserGridTable/index.tsx
  client/src/components/feature/UserInfo/index.tsx
  client/src/components/shared/DropDown/index.tsx
  client/src/core/apis/common.ts
  client/src/core/apis/user.ts
  client/src/router/index.tsx
  client/src/router/routePath.ts
  client/src/types/api.ts
  client/yarn.lock
Labels: ✨ Feature

#29 :memo: 파일 위치 변경/ 경로 수정
  client/src/components/feature/CreateUser/index.tsx
  client/src/pages/DetailUser/index.tsx
Labels: 🎨 Structure

#31 [#1, #2] 로그인 페이지 높이조절, sidebar 로그아웃 클릭시 로그인화면으로 이동, interceptors 추가
  client/src/components/layout/Sidebar/index.tsx
  client/src/core/apis/requester.ts
  client/src/pages/Login/index.tsx
Labels: ✨ Feature, 🎨 Structure, 💄 UI

#33 [#14] 사용자 상세 컴포넌트 import 경로 추가
  client/src/core/apis/user.ts
  client/src/hooks/useUser.ts
  client/src/hooks/useUserSetting.ts
  client/src/pages/DetailUser/index.tsx
  client/src/pages/index.ts
  client/src/router/index.tsx
  client/src/types/api.ts
Labels: 🎨 Structure

#34 [#14] 사용자 상세 데이터 관련 커스텀 훅, 업데이트 fetching 함수 추가
  client/src/components/feature/AccountGrid/index.tsx
  client/src/core/apis/account.ts
  client/src/hooks/useUser.ts
  client/src/hooks/useUserInfo.ts
  client/src/hooks/useUserSetting.ts
  client/src/pages/DetailUser/index.tsx
Labels: ✨ Feature, 🎨 Structure

#35 💄[#14] 사용자 생성 UI 수정
  client/src/components/layout/Header/index.tsx
  client/src/components/layout/index.tsx
  client/src/pages/CreateUser/UserInput/index.tsx
  client/src/pages/CreateUser/UserRadio/index.tsx
  client/src/pages/CreateUser/UserSelect/index.tsx
  client/src/pages/CreateUser/index.tsx
Labels: 🎨 Structure, 💄 UI

#36 [#15] 페이지네이션 방법 수정
  client/src/components/shared/Pagenation/index.tsx
  client/src/pages/Account/index.tsx
  client/src/pages/Users/index.tsx
Labels: 🎨 Structure, 💄 UI

#40 Release 1.0.0
  client/src/components/feature/UserGridTable/index.tsx
  client/src/components/shared/Pagenation/index.tsx
  client/src/core/apis/account.ts
  client/src/core/apis/common.ts
  client/src/core/apis/user.ts
  client/src/core/userService.ts
  client/src/pages/Users/index.tsx
  client/src/shared/modal/index.tsx
  client/src/types/api.ts
  client/src/utils/stringUtils.ts
Labels: ✨ Feature, 🌐 API, 🚑 Bugfix
